//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PeopleRegistry.Exception
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PeopleRegistry.Exception.Resources.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string CPF_ALREADY_EXISTS
        {
            get
            {
                return ResourceManager.GetString("CPF_ALREADY_EXISTS", resourceCulture);
            }
        }

        public static string CPF_INVALID_LENGTH
        {
            get
            {
                return ResourceManager.GetString("CPF_INVALID_LENGTH", resourceCulture);
            }
        }

        public static string CPF_REQUIRED
        {
            get
            {
                return ResourceManager.GetString("CPF_REQUIRED", resourceCulture);
            }
        }

        public static string DATEOFBIRTH_FUTURE
        {
            get
            {
                return ResourceManager.GetString("DATEOFBIRTH_FUTURE", resourceCulture);
            }
        }

        public static string DATEOFBIRTH_REQUIRED
        {
            get
            {
                return ResourceManager.GetString("DATEOFBIRTH_REQUIRED", resourceCulture);
            }
        }

        public static string EMAIL_INVALID
        {
            get
            {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }

        public static string NAME_REQUIRED
        {
            get
            {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }

        public static string PERSON_NOT_FOUND
        {
            get
            {
                return ResourceManager.GetString("PERSON_NOT_FOUND", resourceCulture);
            }
        }

        public static string VALIDATION_FAILED
        {
            get
            {
                return ResourceManager.GetString("VALIDATION_FAILED", resourceCulture);
            }
        }

        public static string EMAIL_IN_USE
        {
            get
            {
                return ResourceManager.GetString("EMAIL_IN_USE", resourceCulture);
            }
        }
        public static string INVALID_CREDENTIALS
        {
            get
            {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        public static string INVALID_REFRESH_TOKEN
        {
            get
            {
                return ResourceManager.GetString("INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        public static string USER_NOT_FOUND
        {
            get
            {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}  